# Add 'frontend` label to any change to *.html files
frontend:
- templates/*.html
# Add 'backend` label to any change to *.py files
backend:
- '**/*.py'
# Add 'settings` label to any change to settings.py files
backend:
- 'ProjectX/settings.py'
